Ignore exit code.

diff --git a/.github/workflows/static-analysis.yml b/.github/workflows/static-analysis.yml
--- a/.github/workflows/static-analysis.yml
+++ b/.github/workflows/static-analysis.yml
@@ -72,13 +72,9 @@ jobs:
       # Parse the results and generate an HTML report.
       - name: Generate HTML report
         run: |
-          CodeChecker parse --export html --output ./reports_html ./results
-
-          # CodeChecker returns 0 if no bugs were found, 1 if it crashed and 2 if it found bugs.
-          if [ $? -eq 1]; then
-            echo "CodeChecker crashed."
-            exit 1
-          fi
+          # The parse command returns with exit code 2 if it finds any bugs.
+          # Thus, we ignore the exit code with "|| true", to avoid failing the workflow.
+          CodeChecker parse --export html --output ./reports_html ./results || true
 
       # Lastly, upload the results to the CI.
       - name: Upload results
